General:
  reaction_rules_path: /home/dima/projects/synto/synto_data/reaction_rules.pickle
  building_blocks_path: /home/dima/projects/synto/synto_data/building_blocks.pickle
Tree:
  ucb_type: uct
  c_usb: 0.1
  max_depth: 6
  max_iterations: 50
  max_time: 120
  max_tree_size: 100000
  verbose: true
  evaluation_mode: gcn
  evaluation_agg: max
  backprop_type: muzero
  init_new_node_value: null
  epsilon: 0.0
PolicyNetwork:
  weights_path: /home/dima/projects/synto/synto_data/policy_network.ckpt
  priority_rules_fraction: 0.5
  top_rules: 50
  rule_prob_threshold: 0.0
ValueNetwork:
  weights_path: /home/dima/projects/synto/synto_data/value_network.ckpt
  
