General:
  results_root: synto_training_small
  reaction_rules_path: synto_training_small/reaction_rules/reaction_rules.pickle
  building_blocks_path: synto_training_small/building_blocks/building_blocks.pickle
  num_cpus: 20
  num_gpus: 1
Tree:
  ucb_type: uct
  c_usb: 0.1
  max_depth: 6
  max_iterations: 5
  max_time: 600
  max_tree_size: 1000000
  verbose: false
  evaluation_mode: gcn
  evaluation_agg: max
  backprop_type: muzero
  init_new_node_value: null
  epsilon: 0.0
ReactionRules:
  results_root: synto_training_small/reaction_rules
  reaction_data_path: synto_training_small/reaction_data/reaction_data.rdf
SelfTuning:
  results_root: synto_training_small/value_network
  dataset_path: synto_training_small/value_molecules/value_molecules.sdf
  num_simulations: 1
  batch_size: 5
PolicyNetwork:
  results_root: synto_training_small/policy_network
  dataset_path: synto_training_small/policy_molecules/policy_molecules.sdf
  datamodule_path: synto_training_small/policy_network/policy_dataset.pt
  weights_path: synto_training_small/policy_network/policy_network.ckpt
  top_rules: 50
  priority_rules_fraction: 0.5
  rule_prob_threshold: 0.0
  num_conv_layers: 5
  vector_dim: 512
  dropout: 0.4
  learning_rate: 0.0005
  num_epoch: 100
  batch_size: 500
ValueNetwork:
  results_root: synto_training_small/value_network
  weights_path: synto_training_small/value_network/value_network.ckpt
  num_conv_layers: 5
  vector_dim: 512
  dropout: 0.4
  learning_rate: 0.0005
  num_epoch: 5
  batch_size: 500
