General:
  results_root: synto_training_small
  reaction_rules_path: synto_training_small/reaction_rules/reaction_rules.pickle
  building_blocks_path: synto_training_small/building_blocks/building_blocks.pickle
  num_cpus: 10
  num_gpus: 1
Tree:
  max_depth: 6
  max_iterations: 5
  evaluation_mode: gcn
  verbose: false
ReactionRules:
  results_root: synto_training_small/reaction_rules
  reaction_data_path: synto_training_small/reaction_data/reaction_data.rdf
SelfTuning:
  results_root: synto_training_small/value_network
  dataset_path: synto_training_small/value_molecules/value_molecules.sdf
PolicyNetwork:
  results_root: synto_training_small/policy_network
  dataset_path: synto_training_small/policy_molecules/policy_molecules.sdf
  datamodule_path: synto_training_small/policy_network/policy_dataset.pt
  weights_path: synto_training_small/policy_network/policy_network.ckpt
ValueNetwork:
  results_root: synto_training_small/value_network
  weights_path: synto_training_small/value_network/value_network.ckpt
