General:
  num_cpus: 5
  num_gpus: 1
InputData:
  reaction_rules_path: synto_planning_data/reaction_rules.pickle
  building_blocks_path: synto_planning_data/building_blocks.smi
PolicyNetwork:
  weights_path: synto_planning_data/policy_network.ckpt
  priority_rules_fraction: 0.5
  top_rules: 50
  rule_prob_threshold: 0.0
ValueNetwork:
  weights_path: synto_planning_data/value_network.ckpt
Tree:
  ucb_type: uct
  c_usb: 0.1
  max_depth: 6
  max_iterations: 50
  max_time: 120
  max_tree_size: 100000
  verbose: true
  evaluation_mode: gcn
  evaluation_agg: max
  backprop_type: muzero
  init_new_node_value: null

  
