General:
  num_cpus: 10
  num_gpus: 1
  targets_path: tests/targets.smi
  results_root: tests/synto_planning_results
InputData:
  reaction_rules_path: tests/synto_trained_models/reaction_rules/reaction_rules_filtered.pickle
  building_blocks_path: tests/synto_training_data_small/building_blocks/building_blocks.smi
  standardize_building_blocks: true
PolicyNetwork:
  weights_path: tests/synto_trained_models/policy_network/weights/policy_network.ckpt
  priority_rules_fraction: 0.5
  top_rules: 50
  rule_prob_threshold: 0.0
ValueNetwork:
  weights_path: tests/synto_trained_models/value_network/weights/value_network.ckpt
Tree:
  ucb_type: uct
  c_ucb: 0.1
  max_depth: 9
  max_iterations: 100
  max_time: 1200
  max_tree_size: 100000
  silent: true
  evaluation_mode: gcn
  evaluation_agg: max
  backprop_type: muzero
  init_node_value: 0.0
