General:
  num_cpus: 5
  num_gpus: 1
  results_root: synto_training_test
InputData:
  building_blocks_path: synto_training_test/building_blocks/building_blocks.smi
  policy_data_path: synto_training_test/policy_molecules/policy_molecules.smi
  reaction_data_path: synto_training_test/reaction_data/reaction_data.rdf
  value_data_path: synto_training_test/value_molecules/value_molecules.smi
DataCleaning:
  clean_reactions: true
ReactionRules:
  min_popularity: 5
Tree:
  backprop_type: muzero
  c_usb: 0.1
  evaluation_agg: max
  evaluation_mode: gcn
  init_new_node_value: null
  max_depth: 6
  max_iterations: 15
  max_time: 600
  max_tree_size: 1000000
  ucb_type: uct
  verbose: false
SelfTuning:
  batch_size: 5
  num_simulations: 1
PolicyNetwork:
  batch_size: 500
  dropout: 0.4
  learning_rate: 0.0005
  num_conv_layers: 5
  num_epoch: 100
  priority_rules_fraction: 0.5
  rule_prob_threshold: 0.0
  top_rules: 50
  vector_dim: 512
ValueNetwork:
  batch_size: 500
  dropout: 0.4
  learning_rate: 0.0005
  num_conv_layers: 5
  num_epoch: 100
  vector_dim: 512